---
# Ansible playbook to prepare which Vim plugins will be used

- name: Set names of excluded plugins
  set_fact: names_of_excluded_plugins="{{ vimansible_excluded_plugins|default([])|map(attribute='name')|list|default([])|unique }}"

- name: Create directory to store Vundle plugins declarations
  file: path={{ vimansible_vim_home_dir_full_path }}/vundle_plugins state=directory

- name: Generate declarations for default Vundle plugins
  template: src=vundle/plugin_declaration.j2 dest={{ vimansible_vim_home_dir_full_path }}/vundle_plugins/{{ item.name }}.vim
  with_items: vimansible_default_plugins
  when: vimansible_default_plugins is defined and vimansible_default_plugins|length > 0
        and item.name not in names_of_excluded_plugins
        and vimansible_plugin_manager == 'vundle'

- name: Generate declarations for more Vundle plugins
  template: src=vundle/plugin_declaration.j2 dest={{ vimansible_vim_home_dir_full_path }}/vundle_plugins/{{ item.name }}.vim
  with_items: vimansible_more_plugins
  when: vimansible_more_plugins is defined and vimansible_more_plugins|length > 0
        and item.name not in names_of_excluded_plugins
        and vimansible_plugin_manager == 'vundle'
